import Header from "@/_components/organisms/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "de" }];
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  let messages;
  try {
    messages = (await import(`../../messages/${params?.locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  return (
    <html lang={params?.locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={params?.locale} messages={messages}>
          <Header />
          <div className="mt-36">{children}</div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
